services:
  pulsar:
    image: apachepulsar/pulsar:3.3.0
    restart: on-failure
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsar-data:/pulsar/data
      - pulsar-conf:/pulsar/conf
    entrypoint: bin/pulsar standalone
# https://docs.docker.com/reference/compose-file/volumes/
volumes:
  pulsar-data:
    driver: local
  pulsar-conf:
    driver: local